### ISSUE TITLE
Settings should be in a separate file

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#1] opened 2011-06-18 06:45 UTC
Amazing work you're doing here, it needs some publicity!

Having the user edit settings inside the script then breaks things when they want to `git pull` to keep up to date.

I suggest keeping the settings in a separate file that people can edit. In my project NoNonsenseForum, the script tries to include a file "config.php", then it sets defaults for any variables still undefined. In the download a config.example.php is provided for people to customise, but there exists not "config.php" in the git repository, so that once a user has configured their settings, they can safely git pull and not have to re-do anything.

I hope that was clear :S

**Comment by spikegrobstein** [comment] 2011-06-18 14:45
I agree. You make some good points.

Last night I added support for providing the `MINECRAFT_SERVER_PATH` as an environment variable that you can define outside of the script and if it's set, mcwrapper will use that. My plan for the future was to support a config file, but one issue with writing this in bash is that in OSX, there's no easy way to find the path to the currently running script, so reading a config file that lives in the same directory as mcwrapper is difficult without one-lining some python (or other language) in there.

How does this sound: mcwrapper will look for a config in a handful of places in decreasing priority and if it doesn't find it, it will fall back to default settings. For example:
1. check for existence of `MCWRAPPER_CONFIG` env variable
2. check for `~/.mcwrapperrc`
3. check for `/etc/mcwrapperrc`

Any other location you think would be good for this? Do you think I should support overriding more options via env variables?

The mcwrapperrc file would define settings for mcbackup as well.

**Comment by Kroc** [comment] 2011-06-18 14:59
`cd "`dirname "$0"`"` changes the path to the directory of the current script.

I would keep the config file in the same directory as everything else. It just makes it harder for inexperienced users if mcwrapper is spread all over the place. I like software to be copy-paste-run. For simplicity, mcwrapper should function if placed in the same directory as the minecraft server jar.

Instead of falling back to defaults if a config is not found, you should check each variable and set default if it is not defined. This way, when you add new variables in the future, the default value will be used rather than NULL—should users not update their config files with the new variable.

**Comment by spikegrobstein** [comment] 2011-06-18 15:19
wow. I SWEAR that didn't work for some reason in the past in OSX. I've gotta test this more and update some other scripts. I always fell back on python. I think I was using the `readlink` trick which works differently in OSX and Linux. Thanks for the insight.

Next update will have this functionality and if placed in the same directory as minecraft_server.jar, it will work from there, too. Gotta refactor a little code to get that all to work properly, though.

I'm still going to have it search in a couple places for the config. It never hurts to support an "installation" of the app.

**Comment by spikegrobstein** [comment] 2011-06-21 02:29
so I got this 99% coded and I'm doing testing and I run into a bug in my code which is why I was using the `readlink` trick and wound up falling back on python in OSX.

The issue is when you `./mcwrapper`. What happens is `dirname $0` returns "." which breaks when I have to `cd` into the directory with `minecraft_server.jar` because it's not smart enough to create the world files in the same directory as it (and always creates them in your current working directory).

I should have a fix for this, just giving you a heads up. =)

**Comment by spikegrobstein** [comment] 2011-06-21 02:32
actually. scratch that. I don't know how to fix that off the top of my head. Gonna fix docs to say that stuff is relative to minecraft_server.jar rather than mcwrapper. 

EDIT: nevermind. this is going to be inconsistent. I'll make this a known issue.

**Comment by spikegrobstein** [comment] 2011-06-21 02:55
again, scratch that. It's fixed. This update has been tagged 1.2.0. Check out the new quickstart.

**Closed as completed by spikegrobstein** 2011-06-21 02:55 UTC

**Comment by Kroc** [comment] 2011-06-21 07:05
superb work. When I can wrestle some time I’ve got a lot more suggestions to provide.

**Comment by spikegrobstein** [comment] 2011-06-21 13:40
awesome. keep them coming.

outside of integrating some of this work into mcbackup and creating init/launchd scripts, I'm out of ideas.

any idea how I should go about publicizing this?

**Comment by Kroc** [comment] 2011-06-21 17:29
I happen to have a website that gets anything from 60–120K unique visits a month :P But it’s not all Minecraft users. It won't be right now but I will think about trying to direct some publicity this way. I think the script needs more usability yet; remember that as much as UNIX admins might want to use this, so will 12 year old Minecraft players who want to set up their rad server for their mates. I’ll file issues with my suggestions, just close the ones you don’t like / agree with / are out-of-scope.
